version: '3.8'

services:
  # PostgreSQL Database for development
  postgres:
    image: postgres:16-alpine
    container_name: omnireach_postgres_dev
    environment:
      POSTGRES_USER: omnireach
      POSTGRES_PASSWORD: omnireach_dev_password
      POSTGRES_DB: omnireach_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omnireach"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: omnireach_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
  redis_dev_data:
